name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12 Pro Max']
          
    steps:
    - uses: actions/checkout@v2
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_12.4.app
    - name: Build
      run: xcodebuild clean build -scheme WKWebViewBrowser -destination "${{ matrix.destination }}"
    - name: Run tests
      run: xcodebuild test -scheme WKWebViewBrowser -destination "${{ matrix.destination }}"
